---
name: Admiral Workflows

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - devel
      - pre-release
  pull_request:
    branches:
      - main
      - devel
      - pre-release
  pull_request_review:
    types: [submitted]
  release:
    types: [published]

concurrency:
  group: admiral-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  style:
    name: Code Style ðŸ‘š
    uses: pharmaverse/admiraltemplate/.github/workflows/style.yaml@main
    if: >
      github.event_name == "push" || github.event_name == "pull_request"
  spellcheck:
    name: Spelling ðŸ†Ž
    uses: pharmaverse/admiraltemplate/.github/workflows/spellcheck.yaml@main
    if: >
      github.event_name == "push" || github.event_name == "pull_request"
  readme:
    name: Render README ðŸ‘“
    uses: pharmaverse/admiraltemplate/.github/workflows/readme-render.yaml@main
    if: github.event_name == "push"
  validation:
    name: Validation ðŸ§§
    uses: pharmaverse/admiraltemplate/.github/workflows/r-pkg-validation.yaml@main
    if: github.event_name == "release"
  check:
    name: Check ðŸ
    uses: pharmaverse/admiraltemplate/.github/workflows/r-cmd-check.yaml@main
    if: >
      github.event_name == "push" || github.event_name == "pull_request"
  docs:
    name: Documentation ðŸ“–
    uses: pharmaverse/admiraltemplate/.github/workflows/pkgdown.yaml@main
    if: github.event_name == "push"
  linter:
    name: Lint ðŸ§¶
    uses: pharmaverse/admiraltemplate/.github/workflows/lintr.yaml@main
    if: >
      github.event_name == "push" || github.event_name == "pull_request"
  links:
    name: Links ðŸ”—
    uses: pharmaverse/admiraltemplate/.github/workflows/links.yaml@main
    if: >
      github.event_name == "push" || github.event_name == "pull_request"
  coverage:
    name: Code Coverage ðŸ§ª
    uses: pharmaverse/admiraltemplate/.github/workflows/code-coverage.yaml@main
    if: >
      github.event_name == "push" || github.event_name == "pull_request"
  templates:
    name: Check Templates ðŸ”Ž
    uses: pharmaverse/admiraltemplate/.github/workflows/check-templates.yaml@main
    if: >
      github.event_name == "push" || github.event_name == "pull_request"
