on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - devel

name: lint

jobs:
  linter:
    name: SuperLinter ğŸ¦¸â€â™€ï¸
    uses: insightsengineering/r.pkg.template/.github/workflows/linter.yaml@main
